Algoritmo "nomeeidade"

Var

   nome : inteiro
   anonasc : inteiro
   anoatual : inteiro
   operacao : real
   idade : real
   

Inicio
      escreva ("Qual o seu nome?")
      leia (nome)
      
      escreva ("qual o seu ano de nascimento?")
      leia (anonasc)

      escreva ("em qual ano estamos?")
      leia (anoatual)
      
      Idade <- anoatual - anonasc
      
      escreva ("A sua idade é ", idade)

Fimalgoritmo